server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # ESSA LINHA DENTRO DO SEU FRONTEND EVITA O 404 NO REFRESH/LINK DO E-MAIL
        try_files $uri $uri/ /index.html;
    }
}
